'use client';

import {
    ShoppingCart, Coffee, Briefcase, Car, Home, Plane, Heart, Music, Film, Book,
    Gift, Utensils, ShoppingBag, Wallet, CreditCard, DollarSign, TrendingUp, TrendingDown,
    Zap, Smartphone, Monitor, Gamepad2, Dumbbell, Pill, Stethoscope, GraduationCap,
    Bus, Train, Fuel, PartyPopper, Beer, Wine, Pizza, Sandwich, Shirt, Scissors,
    Wrench, Lightbulb, Droplets, Wifi, Receipt, Building, Baby, Dog, Cat,
    Sparkles, Star, Globe, MapPin, Camera, Headphones, Tv, Laptop, Watch,
    Umbrella, Sun, Moon, Cloud, Flower2, TreeDeciduous, Mountain, Waves,
    Anchor, Bike, Truck, Ship, Rocket, Trophy, Medal, Target, Flag,
    Palette, Brush, PenTool, Bookmark, FileText, Newspaper, Mail, MessageCircle,
    Bell, Calendar, Clock, Timer, Banknote, PiggyBank, Coins, CircleDollarSign,
    BadgePercent, Tag, ShoppingBasket, Package, Box, Archive, Folder,
    type LucideIcon
} from 'lucide-react';
import React from 'react';

// Short codes that fit in varchar(10) - max 10 characters each
// Map short codes to Lucide icons
const iconMap: Record<string, LucideIcon> = {
    // Original icons
    'cart': ShoppingCart,
    'coffee': Coffee,
    'work': Briefcase,
    'car': Car,
    'home': Home,
    'plane': Plane,
    'heart': Heart,
    'music': Music,
    'film': Film,
    'book': Book,
    'gift': Gift,
    'food': Utensils,
    'shop': ShoppingBag,
    'wallet': Wallet,
    'card': CreditCard,
    'money': DollarSign,
    'up': TrendingUp,
    'down': TrendingDown,
    'zap': Zap,
    'phone': Smartphone,
    'pc': Monitor,
    'game': Gamepad2,
    'gym': Dumbbell,
    'pill': Pill,
    'doctor': Stethoscope,
    'edu': GraduationCap,
    'bus': Bus,
    'train': Train,
    'fuel': Fuel,
    'party': PartyPopper,
    'beer': Beer,
    'wine': Wine,
    'pizza': Pizza,
    'snack': Sandwich,
    'shirt': Shirt,
    'cut': Scissors,
    'tool': Wrench,
    'light': Lightbulb,
    'water': Droplets,
    'wifi': Wifi,
    'bill': Receipt,
    'rent': Building,
    'baby': Baby,
    'dog': Dog,
    'cat': Cat,
    // New icons for more variety
    'star': Star,
    'sparkle': Sparkles,
    'globe': Globe,
    'pin': MapPin,
    'camera': Camera,
    'audio': Headphones,
    'tv': Tv,
    'laptop': Laptop,
    'watch': Watch,
    'umbrella': Umbrella,
    'sun': Sun,
    'moon': Moon,
    'cloud': Cloud,
    'flower': Flower2,
    'tree': TreeDeciduous,
    'mountain': Mountain,
    'waves': Waves,
    'anchor': Anchor,
    'bike': Bike,
    'truck': Truck,
    'ship': Ship,
    'rocket': Rocket,
    'trophy': Trophy,
    'medal': Medal,
    'target': Target,
    'flag': Flag,
    'art': Palette,
    'brush': Brush,
    'pen': PenTool,
    'bookmark': Bookmark,
    'doc': FileText,
    'news': Newspaper,
    'mail': Mail,
    'chat': MessageCircle,
    'bell': Bell,
    'calendar': Calendar,
    'clock': Clock,
    'timer': Timer,
    'cash': Banknote,
    'piggy': PiggyBank,
    'coins': Coins,
    'dollar': CircleDollarSign,
    'percent': BadgePercent,
    'tag': Tag,
    'basket': ShoppingBasket,
    'package': Package,
    'box': Box,
    'archive': Archive,
    'folder': Folder,
};

export const AVAILABLE_ICONS = Object.keys(iconMap);

// Spanish labels for icons
export const iconLabels: Record<string, string> = {
    'cart': 'Compras',
    'coffee': 'Café',
    'work': 'Trabajo',
    'car': 'Coche',
    'home': 'Hogar',
    'plane': 'Viajes',
    'heart': 'Salud',
    'music': 'Música',
    'film': 'Cine',
    'book': 'Libros',
    'gift': 'Regalos',
    'food': 'Restaurante',
    'shop': 'Moda',
    'wallet': 'Dinero',
    'card': 'Tarjeta',
    'money': 'Ingreso',
    'up': 'Inversión',
    'down': 'Pérdida',
    'zap': 'Electricidad',
    'phone': 'Móvil',
    'pc': 'Tecnología',
    'game': 'Juegos',
    'gym': 'Gym',
    'pill': 'Farmacia',
    'doctor': 'Médico',
    'edu': 'Estudios',
    'bus': 'Bus',
    'train': 'Tren',
    'fuel': 'Gasolina',
    'party': 'Ocio',
    'beer': 'Bar',
    'wine': 'Vino',
    'pizza': 'Comida',
    'snack': 'Snack',
    'shirt': 'Ropa',
    'cut': 'Peluquería',
    'tool': 'Reparación',
    'light': 'Luz',
    'water': 'Agua',
    'wifi': 'Internet',
    'bill': 'Facturas',
    'rent': 'Alquiler',
    'baby': 'Niños',
    'dog': 'Mascotas',
    'cat': 'Gato',
    // New icon labels
    'star': 'Favorito',
    'sparkle': 'Especial',
    'globe': 'Mundo',
    'pin': 'Ubicación',
    'camera': 'Foto',
    'audio': 'Audio',
    'tv': 'TV',
    'laptop': 'Portátil',
    'watch': 'Reloj',
    'umbrella': 'Lluvia',
    'sun': 'Sol',
    'moon': 'Noche',
    'cloud': 'Nube',
    'flower': 'Flores',
    'tree': 'Naturaleza',
    'mountain': 'Montaña',
    'waves': 'Playa',
    'anchor': 'Náutico',
    'bike': 'Bici',
    'truck': 'Transporte',
    'ship': 'Barco',
    'rocket': 'Cohete',
    'trophy': 'Trofeo',
    'medal': 'Logro',
    'target': 'Objetivo',
    'flag': 'Meta',
    'art': 'Arte',
    'brush': 'Pintura',
    'pen': 'Diseño',
    'bookmark': 'Guardado',
    'doc': 'Documento',
    'news': 'Noticias',
    'mail': 'Correo',
    'chat': 'Chat',
    'bell': 'Alertas',
    'calendar': 'Evento',
    'clock': 'Tiempo',
    'timer': 'Cronómetro',
    'cash': 'Efectivo',
    'piggy': 'Ahorro',
    'coins': 'Monedas',
    'dollar': 'Dólar',
    'percent': 'Descuento',
    'tag': 'Etiqueta',
    'basket': 'Cesta',
    'package': 'Paquete',
    'box': 'Caja',
    'archive': 'Archivo',
    'folder': 'Carpeta',
};

type Props = {
    name?: string;
    className?: string;
    fallback?: string;
    style?: React.CSSProperties;
};

export default function CategoryIcon({ name, className = 'w-5 h-5', fallback, style }: Props) {
    // Check if it's an emoji (Unicode emoji characters)
    if (name) {
        const emojiRegex = /[\u{1F300}-\u{1F9FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]/u;
        if (emojiRegex.test(name)) {
            return <span style={style}>{name}</span>;
        }
    }

    // Check if we have a Lucide icon for this code
    if (name && iconMap[name]) {
        const Icon = iconMap[name];
        return <Icon className={className} style={style} />;
    }

    // Fallback to emoji or default
    return <span style={style}>{fallback || name || '💰'}</span>;
}
